apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world
    image: 927286686937.dkr.ecr.us-east-1.amazonaws.com/project:latest
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-port
spec:
  type: NodePort
  ports:
  - name: http
    port: 9011
    targetPort: 9011
    nodePort: 30443
  selector:
    app: hello-world